name: Feature Request
description: Suggest a new feature or enhancement for the action
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! We appreciate your input.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see?
      placeholder: I would like the action to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: I also thought about...

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New LLM Provider Support
        - New Output Format
        - Improved Analysis
        - Better Documentation
        - Performance Enhancement
        - Integration with Tool/Service
        - Other
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: How would this feature be used?
      render: yaml
      placeholder: |
        - uses: ianlintner/ai_summary_action@v1
          with:
            new-feature: 'value'

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context or screenshots
      placeholder: Other relevant information...
